openapi: 3.1.0
info:
  title: Notion API - Fixed Page
  description: Personal test for a single hardcoded Notion page.
  version: 1.0.0
servers:
  - url: https://api.notion.com/v1
paths:
  /pages/2880d7d37deb8082baf6cccb334a830d:
    get:
      operationId: getFixedNotionPage
      summary: Retrieve a fixed Notion page
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          example: Bearer ntn_X3620961771at2knhAAXOx8kGlOiIQ9GKV0P9x69MT90xm
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
      responses:
        '200':
          description: Page retrieved
          content:
            application/json:
              schema:
                type: object
    patch:
      operationId: updateFixedNotionPage
      summary: Update a fixed Notion page
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          example: Bearer ntn_X3620961771at2knhAAXOx8kGlOiIQ9GKV0P9x69MT90xm
        - name: Notion-Version
          in: header
          required: true
          schema:
            type: string
          example: 2022-06-28
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  type: object
                archived:
                  type: boolean
      responses:
        '200':
          description: Page updated
          content:
            application/json:
              schema:
                type: object
